In [4]:
import pandas as pd
import numpy as np
# Show all columns
pd.set_option('display.max_columns', None)

data = pd.read_csv('C:/Users/mathi/OneDrive/Skrivebord/2_Sem_Kand/Projekt_Kandidat2/DataPrep.csv')
data

,Unnamed: 0,id,device,from,to,avg_hr,avg_rr,avg_act,calc_data,sleep_score,duration,duration_in_bed,duration_awake,duration_in_sleep,duration_in_rem,duration_in_light,duration_in_deep,duration_sleep_onset,bedexit_duration,sleep_data,bedexit_count,bedexit_data,tossnturn_count,tossnturn_data,from_gmt_offset,min_hr,max_hr,min_rr,max_rr,fm_count,fm_data,awakenings,hrv_data,hrv_score,hrv_lf,hrv_hf,hrv_rmssd_data,hrv_rmssd_evening,hrv_rmssd_morning,temp_v1_uid,patient_ID,AGEBL,GENDER,NYHABL,EFTITBL,EJREHABBL,EJFINISHBL,WEIGHTBL,HEIGHTBL,BPSYSBL,BPDIABL,HRB,from_datetime,"Blodtryk, Systolisk","Blodtryk, Diastolisk",Puls,VÃ¦gt,Skridt
0,0,5f7e0ab04a207808e008dac6,1EFD48,1602086420,1602095731,58.6,9.1,285.9,"[[1602086424,null,null,757],[1602086428,null,n...",18.0,9311,9311,2430.0,6870.0,1740.0,4380.0,750.0,1230.0,0,"[[1602086439,4],[1602087639,2],[1602089829,1],...",0,NaN,75,"[1602086436,1602086496,1602086512,1602086528,1...",180,51.0,110.0,4.0,20.0,0,NaN,0.0,"[[36.5,33.5,-2.9,0.92,-1.95],[36.1,32.6,-3.4,0...",48.0,15.0,85.0,"[[1602087771,48,13,87,0,156],[1602087951,37,14...",36.5,33.5,NaN,431,76.0,0.0,2.0,30.0,35.0,35.0,74.1,192.0,130.0,45.0,59.0,2020-10-07 16:00:20,160.0,69.0,65.0,78.250000,862.0
1,1,5f7ec3b3765d9b08e03c5211,1EFD48,1602104992,1602143148,62.9,16.4,313.6,"[[1602104996,null,null,110],[1602105000,null,n...",84.0,38156,38156,10110.0,27990.0,4830.0,16440.0,6720.0,1500.0,0,"[[1602105011,4],[1602106481,2],[1602107231,1],...",0,NaN,299,"[1602105000,1602105020,1602105084,1602105120,1...",180,49.0,122.0,5.0,24.0,3,"[1602126450,1602129851,1602134789]",0.0,"[[55.4,51.9,-3.5,0.94,-0.46],[52.4,48.8,-3.7,0...",60.0,21.0,79.0,"[[1602106522,25,18,82,0,206],[1602106702,25,17...",55.4,51.9,NaN,431,76.0,0.0,2.0,30.0,35.0,35.0,74.1,192.0,130.0,45.0,59.0,2020-10-07 21:09:52,160.0,69.0,65.0,78.250000,862.0
2,2,5f7f6eae2eb84708e0d88f54,1EFD48,1602175075,1602186881,58.8,7.8,134.1,"[[1602175076,null,null,86],[1602175080,null,nu...",23.0,11806,11806,3570.0,8220.0,1680.0,5040.0,1500.0,2130.0,0,"[[1602175091,4],[1602177191,2],[1602178391,1],...",0,NaN,66,"[1602175096,1602175112,1602175128,1602175156,1...",180,53.0,77.0,4.0,20.0,0,NaN,0.0,"[[67.0,35.3,-31.7,0.53,-23.50],[49.0,49.0,0.0,...",70.0,36.0,64.0,"[[1602177325,70,40,60,0,132],[1602178586,61,37...",67.0,35.3,NaN,431,76.0,0.0,2.0,30.0,35.0,35.0,74.1,192.0,130.0,45.0,59.0,2020-10-08 16:37:55,140.0,55.0,64.0,76.199997,2865.0
3,3,5f7ff574b2cf6908e0d28fcf,1EFD48,1602191290,1602221363,59.6,16.2,268.9,"[[1602191292,null,null,80],[1602191296,null,nu...",74.0,30073,28603,4710.0,25350.0,3960.0,16800.0,4590.0,1680.0,1470,"[[1602191307,4],[1602192957,2],[1602195057,1],...",2,"[[1602221090,1602220063],[1602211152,1602210709]]",167,"[1602191520,1602191732,1602191748,1602191780,1...",180,51.0,120.0,7.0,26.0,0,NaN,2.0,"[[43.2,4.7,-38.5,0.11,-5.19],[39.5,36.2,-3.2,0...",36.0,19.0,81.0,"[[1602193181,22,25,75,0,232],[1602193361,26,22...",43.2,4.7,NaN,431,76.0,0.0,2.0,30.0,35.0,35.0,74.1,192.0,130.0,45.0,59.0,2020-10-08 21:08:10,140.0,55.0,64.0,76.199997,2865.0
4,4,5f81553968df9708e069c7b1,1EFD48,1602278207,1602311453,60.3,16.1,285.7,"[[1602278210,null,null,172],[1602278214,null,n...",77.0,33246,31364,7920.0,25320.0,4080.0,14700.0,6540.0,1620.0,1882,"[[1602278225,4],[1602279815,2],[1602280805,1],...",3,"[[1602309892,1602308800],[1602305244,160230482...",327,"[1602278262,1602278526,1602278550,1602278566,1...",180,51.0,128.0,6.0,26.0,1,[1602285137],2.0,"[[52.4,30.4,-21.9,0.58,-2.75],[48.6,30.0,-18.6...",43.0,18.0,82.0,"[[1602279917,38,19,81,0,229],[1602280097,42,18...",52.4,30.4,NaN,431,76.0,0.0,2.0,30.0,35.0,35.0,74.1,192.0,130.0,45.0,59.0,2020-10-09 21:16:47,145.0,54.0,64.0,75.800003,3634.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5590,5590,63fc11f76984a917887113e4,1C6994,1677443559,1677464007,68.7,15.6,372.2,"[[1677443563,null,null,248],[1677443567,null,n...",55.0,20448,20272,2490.0,17940.0,4740.0,10170.0,3030.0,660.0,176,"[[1677443578,4],[1677444208,2],[1677445108,3],...",1,"[[1677460017,1677459841]]",129,"[1677443579,1677443591,1677443607,1677443623,1...",120,52.0,97.0,12.0,26.0,0,NaN,1.0,"[[26.5,25.6,-0.9,0.97,-0.17],[26.0,25.6,-0.3,0...",42.0,57.0,43.0,"[[1677444369,17,71,29,1,72],[1677444549,18,69,...",26.5,25.6,NaN,554,74.0,0.0,2.0,20.0,NaN,NaN,74.0,183.0,116.0,72.0,74.0,2023-02-26 20:32:39,142.0,70.0,62.0,77.550003,NaN
5591,5591,63fd6a99c578671848ceca64,1C6994,1677533318,1677552131,63.2,15.4,317.2,"[[1677533321,null,null,4],[1677533325,null,nul...",47.0,18813,18459,3120.0,15690.0,4320.0,8760.0,2610.0,720.0,354,"[[1677533336,4],[1677534026,2],[1677535556,1],...",2,"[[1677551292,1677551100],[1677533585,1677533423]]",74,"[1677533589,1677533613,1677533625,1677533641,1...",120,48.0,90.0,13.0,19.0,0,NaN,1.0,"[[31.2,24.2,-7.1,0.77,-1.58],[33.0,29.2,-3.8,0...",33.0,53.0,47.0,"[[1677534034,58,65,35,1,537],[1677534214,51,58...",31.2,24.2,NaN,554,74.0,0.0,2.0,20.0,NaN,NaN,74.0,183.0,116.0,72.0,74.0,2023-02-27 21:28:38,NaN,NaN,NaN,78.500000,NaN
5592,5592,63febaf55a97a71848062b68,1C6994,1677616071,1677638369,69.1,15.5,204.5,"[[1677616073,null,null,0],[1677616077,null,nul...",68.0,22298,22236,990.0,21300.0,4260.0,13140.0,3900.0,630.0,62,"[[1677616088,4],[1677616688,2],[1677617228,3],...",1,"[[1677616157,1677616095]]",64,"[1677616105,1677616177,1677616253,1677616285,1...",120,56.0,79.0,9.0,20.0,0,NaN,0.0,"[[36.2,15.7,-20.5,0.43,-3.51],[37.0,21.5,-15.5...",28.0,55.0,45.0,"[[1677616786,34,39,61,1,134],[1677616966,32,43...",36.2,15.7,NaN,554,74.0,0.0,2.0,20.0,NaN,NaN,74.0,183.0,116.0,72.0,74.0,2023-02-28 20:27:51,NaN,NaN,NaN,78.750000,NaN
5593,5593,640001b55d34f61848e4dbba,1C6994,1677702052,1677721997,64.8,15.4,434.6,"[[1677702056,null,null,23313],[1677702060,null...",57.0,19945,19945,1740.0,18210.0,6390.0,9390.0,2430.0,870.0,0,"[[1677702071,4],[1677702911,2],[1677704021,3],...",0,NaN,82,"[1677702060,1677702076,1677702128,1677702156,1...",120,51.0,121.0,12.0,19.0,0,NaN,0.0,"[[28.2,17.7,-10.4,0.63,-2.09],[23.8,20.4,-3.4,...",24.0,60.0,40.0,"[[1677703042,20,51,49,0,91],[1677703223,21,49,...",28.2,17.7,NaN,554,74.0,0.0,2.0,20.0,NaN,NaN,74.0,183.0,116.0,72.0,74.0,2023-03-01 20:20:52,128.0,73.0,65.0,78.250000,NaN
5594,5594,64015d96c4832e1848f376ad,1C6994,1677790627,1677811024,61.9,15.6,327.5,"[[1677790631,null,null,256],[1677790635,null,n...",63.0,20397,20397,960.0,19440.0,4920.0,11070.0,3450.0,780.0,0,"[[1677790646,4],[1677791396,2],[1677792596,3],...",0,NaN,73,"[1677790643,1677790683,1677790699,1677790735,1...",120,48.0,97.0,13.0,26.0,0,NaN,0.0,"[[19.0,25.6,6.5,1.34,1.22],[19.2,22.1,2.9,1.15...",62.0,52.0,48.0,"[[1677791437,19,44,56,0,182],[1677791617,21,42...",19.0,25.6,NaN,554,74.0,0.0,2.0,20.0,NaN,NaN,74.0,183.0,116.0,72.0,74.0,2023-03-02 20:57:07,NaN,NaN,NaN,NaN,NaN

### Analyse af calc_data

In [13]:
# Show only calc_data, patient_ID and from_datetime
data = data[['calc_data', 'patient_ID', 'from_datetime']]
data

                                              calc_data  patient_ID  \
0     [[1602086424,null,null,757],[1602086428,null,n...         431
1     [[1602104996,null,null,110],[1602105000,null,n...         431
2     [[1602175076,null,null,86],[1602175080,null,nu...         431
3     [[1602191292,null,null,80],[1602191296,null,nu...         431
4     [[1602278210,null,null,172],[1602278214,null,n...         431
5     [[1602316073,null,null,650],[1602316077,null,n...         431
6     [[1602347703,null,null,315],[1602347707,null,n...         431
7     [[1602536986,null,null,199],[1602536990,null,n...         431
8     [[1602590867,null,null,8614],[1602590871,null,...         431
9     [[1602606191,null,null,209],[1602606195,null,n...         431
10    [[1602709902,null,null,307],[1602709906,null,n...         431
11    [[1602796257,null,null,212],[1602796261,null,n...         431
12    [[1602883113,null,null,379],[1602883117,null,n...         431
13    [[1602968807,null,null,1918],[1602968811,null,...         431
14    [[1603056227,null,null,537],[1603056231,null,n...         431
15    [[1603140854,null,null,499],[1603140858,null,n...         431
16    [[1603228921,57,null,471],[1603228925,54,null,...         431
17    [[1603315521,null,null,150],[1603315525,86,nul...         431
18    [[1603401174,null,null,117],[1603401178,null,n...         431
19    [[1603490547,51,null,58],[1603490551,51,null,8...         431
20    [[1603575138,null,null,149],[1603575142,null,n...         431
21    [[1603575138,null,null,149],[1603575142,null,n...         431
22    [[1603664973,null,null,128],[1603664977,null,n...         431
23    [[1603749927,null,null,178],[1603749931,null,n...         431
24    [[1603837514,null,null,331],[1603837518,null,n...         431
25    [[1603923770,null,null,148],[1603923774,null,n...         431
26    [[1604009519,null,null,217],[1604009523,null,n...         431
27    [[1604097031,null,null,323],[1604097035,null,n...         431
28    [[1604097031,null,null,323],[1604097035,null,n...         431
29    [[1604183431,null,null,1274],[1604183435,null,...         431
30    [[1604268562,null,null,143],[1604268566,null,n...         431
31    [[1604268562,null,null,143],[1604268566,null,n...         431
32    [[1604355561,null,null,3204],[1604355565,null,...         431
33    [[1604442379,null,null,900],[1604442383,null,n...         431
34    [[1604527634,null,null,631],[1604527638,null,n...         431
35    [[1604614821,null,null,96],[1604614825,null,nu...         431
36    [[1604701508,null,null,55],[1604701512,null,nu...         431
37    [[1604786632,null,null,104],[1604786636,null,n...         431
38    [[1604873671,null,null,514],[1604873675,null,n...         431
39    [[1604960605,null,null,84],[1604960609,null,nu...         431
40    [[1605047360,null,null,3025],[1605047364,null,...         431
41    [[1605133793,null,null,107],[1605133797,57,nul...         431
42    [[1605220374,null,null,1106],[1605220378,null,...         431
43    [[1605306897,null,null,123],[1605306901,null,n...         431
44    [[1605392360,null,null,885],[1605392364,null,n...         431
45    [[1605478499,67,null,64],[1605478503,null,null...         431
46    [[1605564986,null,null,130],[1605564990,null,n...         431
47    [[1605652060,null,null,575],[1605652064,null,n...         431
48    [[1605737680,null,null,927],[1605737684,null,n...         431
49    [[1605824244,null,null,94],[1605824248,null,nu...         431
50    [[1605910444,null,null,1364],[1605910448,null,...         431
51    [[1605997919,59,null,128],[1605997923,60,null,...         431
52    [[1606082803,null,null,86],[1606082807,null,nu...         431
53    [[1606170193,null,null,99],[1606170197,null,nu...         431
54    [[1606256374,null,null,169],[1606256378,null,n...         431
55    [[1606342810,null,null,19],[1606342814,null,nu...         431
56    [[1606429058,null,null,141],[1606429062,null,n...         431
57    [[1606516101,null,null,509],[1606516105,null,n...         431
58    [[1606603222,null,null,454],[1606603226,null,n...         431
59    [[1606689018,null,null,9655],[1606689022,null,...         431
60    [[1606774626,null,null,114],[1606774630,null,n...         431
61    [[1606862335,null,null,59],[1606862339,null,nu...         431
62    [[1606946034,null,null,495],[1606946038,null,n...         431
63    [[1607032729,null,null,1175],[1607032733,null,...         431
64    [[1607120494,null,null,1139],[1607120498,null,...         431
65    [[1607208047,null,null,530],[1607208051,null,n...         431
66    [[1607292930,null,null,189],[1607292934,null,n...         431
67    [[1607292930,null,null,189],[1607292934,null,n...         431
68    [[1607379482,null,null,587],[1607379486,null,n...         431
69    [[1607379482,null,null,587],[1607379486,null,n...         431
70    [[1607465246,null,null,133],[1607465250,null,n...         431
71    [[1607552699,90,null,86],[1607552703,90,null,2...         431
72    [[1607638682,null,null,86],[1607638686,null,nu...         431
73    [[1607638682,null,null,86],[1607638686,null,nu...         431
74    [[1607726998,null,null,120],[1607727002,null,n...         431
75    [[1607812804,null,null,10713],[1607812808,null...         431
76    [[1607898352,null,null,1431],[1607898356,null,...         431
77    [[1607984899,null,null,173],[1607984903,null,n...         431
78    [[1608071596,null,null,171],[1608071600,56,nul...         431
79    [[1608156879,null,null,149],[1608156883,null,n...         431
80    [[1608243747,null,null,113],[1608243782,null,n...         431
81    [[1608330118,null,null,561],[1608330122,null,n...         431
82    [[1608417569,null,null,186],[1608417573,null,n...         431
83    [[1608504117,null,null,306],[1608504121,null,n...         431
84    [[1608589229,63,null,254],[1608589233,67,null,...         431
85    [[1608675517,null,null,415],[1608675521,null,n...         431
86    [[1608761404,null,null,217],[1608761408,null,n...         431
87    [[1608850151,null,null,73],[1608850155,null,nu...         431
88    [[1608935044,59,null,11],[1608935048,66,null,7...         431
89    [[1608935044,59,null,11],[1608935048,66,null,7...         431
90    [[1609021259,null,null,99],[1609021263,null,nu...         431
91    [[1609108018,null,null,110],[1609108022,null,n...         431
92    [[1609193756,null,null,115],[1609193760,null,n...         431
93    [[1609280104,null,null,737],[1609280108,null,n...         431
94    [[1609366401,null,null,881],[1609366405,null,n...         431
95    [[1609459002,null,null,70],[1609459006,null,nu...         431
96    [[1609471450,null,null,44],[1609471454,null,nu...         431
97    [[1609538553,null,null,73],[1609538557,null,nu...         431
98    [[1609626639,null,null,254],[1609626643,null,n...         431
99    [[1609712535,79,null,520],[1609712539,71,null,...         431
100   [[1609799564,null,null,257],[1609799568,null,n...         431
101   [[1609886084,null,null,358],[1609886088,null,n...         431
102   [[1609971960,null,null,386],[1609971964,null,n...         431
103   [[1609971960,null,null,386],[1609971964,null,n...         431
104   [[1610059375,null,null,1463],[1610059379,null,...         431
105   [[1610142538,null,null,2010],[1610142542,null,...         431
106   [[1610142538,null,null,2010],[1610142542,null,...         431
107   [[1610230903,null,null,80],[1610230907,null,nu...         431
108   [[1610318636,null,null,2320],[1610318640,null,...         431
109   [[1610662530,null,null,4667],[1610662534,null,...         431
110   [[1610747861,null,null,2717],[1610747865,null,...         431
111   [[1610836202,null,null,9980],[1610836206,null,...         431
112   [[1610921085,null,null,1892],[1610921089,null,...         431
113   [[1611008060,null,null,189],[1611008064,null,n...         431
114   [[1611094021,null,null,127],[1611094025,null,n...         431
115   [[1611179034,83,null,39],[1611179038,85,null,5...         431
116   [[1611265700,null,null,149],[1611265704,null,n...         431
117   [[1611351841,null,null,133],[1611351845,66,nul...         431
118   [[1611439305,null,null,162],[1611439309,null,n...         431
119   [[1611439305,null,null,162],[1611439309,null,n...         431
120   [[1611525958,null,null,163],[1611525962,null,n...         431
121   [[1611525958,null,null,163],[1611525962,null,n...         431
122   [[1611525958,null,null,163],[1611525962,null,n...         431
123   [[1611611304,60,null,18],[1611611308,60,null,1...         431
124   [[1611611304,60,null,18],[1611611308,60,null,1...         431
125   [[1611698820,null,null,39],[1611698824,null,nu...         431
126   [[1611784692,null,null,67],[1611784727,null,nu...         431
127   [[1611870563,58,null,59],[1611870567,58,null,5...         431
128   [[1612043687,69,null,186],[1612043691,69,null,...         431
129   [[1612217535,null,null,73],[1612217539,null,nu...         431
130   [[1612303641,69,null,71],[1612303645,71,null,3...         431
131   [[1612390360,null,null,331],[1612390364,null,n...         431
132   [[1612476464,58,null,100],[1612476468,58,null,...         431
133   [[1612476464,58,null,100],[1612476468,58,null,...         431
134   [[1612563227,null,null,219],[1612563231,null,n...         431
135   [[1612649538,null,null,236],[1612649542,null,n...         431
136   [[1612649538,null,null,236],[1612649542,null,n...         431
137   [[1612736137,null,null,26],[1612736141,null,nu...         431
138   [[1612822964,69,null,69],[1612822968,69,null,1...         431
139   [[1612909813,null,null,103],[1612909817,null,n...         431
140   [[1612997316,null,null,69],[1612997320,null,nu...         431
141   [[1613082383,null,null,394],[1613082387,null,n...         431
142   [[1613169290,null,null,125],[1613169294,null,n...         431
143   [[1613255490,null,null,308],[1613255494,null,n...         431
144   [[1613342540,67,null,28],[1613342544,67,null,2...         431
145   [[1613425322,null,null,467],[1613425326,null,n...         431
146   [[1613512666,null,null,25],[1613512670,null,nu...         431
147   [[1613598993,null,null,538],[1613598997,null,n...         431
148   [[1613685444,null,null,60],[1613685448,null,nu...         431
149   [[1613772536,null,null,209],[1613772572,null,n...         431
150   [[1613859296,null,null,37],[1613859300,null,nu...         431
151   [[1614030342,null,null,48],[1614030346,85,null...         431
152   [[1614117270,null,null,7239],[1614117274,null,...         431
153   [[1614203442,null,null,169],[1614203446,null,n...         431
154   [[1614290239,null,null,159],[1614290243,null,n...         431
155   [[1614376538,66,null,502],[1614376542,65,null,...         431
156   [[1614376538,66,null,502],[1614376542,65,null,...         431
157   [[1614465953,null,null,314],[1614465957,null,n...         431
158   [[1614550706,null,null,323],[1614550710,null,n...         431
159   [[1614635445,null,null,162],[1614635449,null,n...         431
160   [[1614724683,51,null,17],[1614724687,51,null,1...         431
161   [[1614809665,null,null,78],[1614809669,null,nu...         431
162   [[1614894753,null,null,284],[1614894757,null,n...         431
163   [[1614981240,null,null,648],[1614981244,null,n...         431
164   [[1615069783,null,null,604],[1615069787,null,n...         431
165   [[1615155903,null,null,491],[1615155907,null,n...         431
166   [[1615241002,null,null,993],[1615241006,null,n...         431
167   [[1615328635,null,null,833],[1615328639,null,n...         431
168   [[1615413035,null,null,214],[1615413039,94,nul...         431
169   [[1615501858,null,null,74],[1615501862,null,nu...         431
170   [[1615587083,null,null,1890],[1615587087,null,...         431
171   [[1615674936,null,null,975],[1615674940,null,n...         431
172   [[1615759089,null,null,234],[1615759093,null,n...         431
173   [[1615847180,62,null,542],[1615847184,65,null,...         431
174   [[1615933044,null,null,732],[1615933048,null,n...         431
175   [[1615933044,null,null,732],[1615933048,null,n...         431
176   [[1616017772,null,null,1337],[1616017776,null,...         431
177   [[1616017772,null,null,1337],[1616017776,null,...         431
178   [[1616106040,null,null,216],[1616106044,null,n...         431
179   [[1616193470,null,null,173],[1616193474,null,n...         431
180   [[1616277751,null,null,371],[1616277755,null,n...         431
181   [[1616364305,null,null,416],[1616364309,null,n...         431
182   [[1616450153,53,null,275],[1616450157,64,null,...         431
183   [[1616536480,95,null,308],[1616536484,95,null,...         431
184   [[1616623596,null,null,149],[1616623600,null,n...         431
185   [[1616709040,null,null,412],[1616709044,null,n...         431
186   [[1616797207,null,null,412],[1616797211,null,n...         431
187   [[1616883426,null,null,123],[1616883430,null,n...         431
188   [[1616965874,null,null,130],[1616965878,null,n...         431
189   [[1617051839,null,null,27],[1617051843,null,nu...         431
190   [[1617138914,null,null,132],[1617138918,null,n...         431
191   [[1617158946,null,null,22],[1617158950,null,nu...         431
192   [[1617225681,null,null,96],[1617225685,null,nu...         431
193   [[1617312336,null,null,181],[1617312340,null,n...         431
194   [[1617397724,92,null,532],[1617397760,92,null,...         431
195   [[1617483452,61,null,48],[1617483456,61,null,5...         431
196   [[1617570697,null,null,170],[1617570701,null,n...         431
197   [[1617656173,null,null,49],[1617656177,null,nu...         431
198   [[1617656173,null,null,49],[1617656177,null,nu...         431
199   [[1617743965,null,null,29],[1617744001,null,nu...         431
200   [[1617829978,null,null,645],[1617829982,null,n...         431
201   [[1617916771,null,null,607],[1617916775,null,n...         431
202   [[1618003802,null,null,897],[1618003806,null,n...         431
203   [[1618087278,null,null,917],[1618087282,null,n...         431
204   [[1618175401,null,null,6760],[1618175405,null,...         431
205   [[1618262308,null,null,1609],[1618262312,null,...         431
206   [[1618347910,null,null,1582],[1618347914,null,...         431
207   [[1618434000,null,null,339],[1618434004,null,n...         431
208   [[1618521384,null,null,151],[1618521388,null,n...         431
209   [[1618607732,45,null,60],[1618607736,45,null,1...         431
210   [[1618693083,null,null,99],[1618693087,null,nu...         431
211   [[1618780566,null,null,495],[1618780570,null,n...         431
212   [[1618864330,null,null,2630],[1618864334,null,...         431
213   [[1618952061,null,null,95],[1618952065,null,nu...         431
214   [[1619039037,null,null,293],[1619039041,null,n...         431
215   [[1619124029,80,null,388],[1619124033,80,null,...         431
216   [[1619212210,null,null,84],[1619212214,null,nu...         431
217   [[1619298845,null,null,136],[1619298849,null,n...         431
218   [[1619298845,null,null,136],[1619298849,null,n...         431
219   [[1619384121,null,null,102],[1619384157,null,n...         431
220   [[1619470439,null,null,41],[1619470443,null,nu...         431
221   [[1619470439,null,null,41],[1619470443,null,nu...         431
222   [[1619558351,null,null,163],[1619558355,null,n...         431
223   [[1619558351,null,null,163],[1619558355,null,n...         431
224   [[1619645498,null,null,1789],[1619645502,null,...         431
225   [[1619729245,null,null,586],[1619729249,null,n...         431
226   [[1619729245,null,null,586],[1619729249,null,n...         431
227   [[1619816439,null,null,523],[1619816443,null,n...         431
228   [[1619904355,51,null,2079],[1619904359,53,null...         431
229   [[1619990024,null,null,482],[1619990028,null,n...         431
230   [[1620076792,null,null,451],[1620076796,null,n...         431
231   [[1620162303,null,null,82],[1620162307,null,nu...         431
232   [[1620249771,null,null,73],[1620249775,null,nu...         431
233   [[1620335962,null,null,790],[1620335966,null,n...         431
234   [[1620422132,null,null,3880],[1620422136,null,...         431
235   [[1620507425,null,null,2160],[1620507429,null,...         431
236   [[1620592982,null,null,884],[1620592986,null,n...         431
237   [[1620680832,null,null,6560],[1620680836,null,...         431
238   [[1620767825,null,null,1232],[1620767829,null,...         431
239   [[1620852462,null,null,3507],[1620852466,null,...         431
240   [[1620940556,null,null,41],[1620940560,null,nu...         431
241   [[1621026397,null,null,93],[1621026401,null,nu...         431
242   [[1621111798,null,null,4772],[1621111802,null,...         431
243   [[1621199637,null,null,132],[1621199641,null,n...         431
244   [[1621284722,null,null,1325],[1621284726,null,...         431
245   [[1621373406,null,null,92],[1621373410,null,nu...         431
246   [[1621458890,null,null,1011],[1621458894,null,...         431
247   [[1621546217,null,null,2008],[1621546221,null,...         431
248   [[1621546217,null,null,2008],[1621546221,null,...         431
249   [[1621631521,null,null,218],[1621631525,null,n...         431
250   [[1621631521,null,null,218],[1621631525,null,n...         431
251   [[1621631521,null,null,218],[1621631525,null,n...         431
252   [[1621717786,null,null,102],[1621717790,null,n...         431
253   [[1621804842,null,null,1220],[1621804846,null,...         431
254   [[1621889150,null,null,290],[1621889154,null,n...         431
255   [[1621976547,75,null,133],[1621976551,76,null,...         431
256   [[1622063275,null,null,284],[1622063279,null,n...         431
257   [[1622149099,null,null,61],[1622149103,null,nu...         431
258   [[1622235886,null,null,978],[1622235890,null,n...         431
259   [[1622323714,null,null,351],[1622323718,null,n...         431
260   [[1622407800,57,null,158],[1622407804,59,null,...         431
261   [[1622496027,null,null,285],[1622496031,null,n...         431
262   [[1622582463,null,null,608],[1622582467,null,n...         431
263   [[1622669094,null,null,565],[1622669098,null,n...         431
264   [[1622754994,null,null,191],[1622754998,null,n...         431
265   [[1622841213,69,null,141],[1622841217,69,null,...         431
266   [[1622928957,null,null,307],[1622928961,null,n...         431
267   [[1623013756,null,null,356],[1623013760,null,n...         431
268   [[1623100275,null,null,165],[1623100279,null,n...         431
269   [[1623187014,null,null,433],[1623187018,null,n...         431
270   [[1623273668,null,null,798],[1623273672,null,n...         431
271   [[1623285910,null,null,24],[1623285914,null,nu...         431
272   [[1623350534,null,null,478],[1623350538,null,n...         431
273   [[1623445478,null,null,20],[1623445482,null,nu...         431
274   [[1623532877,null,null,589],[1623532881,null,n...         431
275   [[1623618400,null,null,20540],[1623618404,null...         431
276   [[1623618400,null,null,20540],[1623618404,null...         431
277   [[1623706257,null,null,27],[1623706261,null,nu...         431
278   [[1623792038,null,null,394],[1623792042,null,n...         431
279   [[1623877805,null,null,128],[1623877809,null,n...         431
280   [[1623925615,null,null,86],[1623925619,59,null...         431
281   [[1623964307,null,null,802],[1623964311,null,n...         431
282   [[1624050680,null,null,988],[1624050684,null,n...         431
283   [[1624138425,null,null,10201],[1624138429,null...         431
284   [[1624223417,null,null,1019],[1624223421,null,...         431
285   [[1603153197,null,null,519],[1603153201,null,n...         435
286   [[1603232136,94,null,408],[1603232140,94,null,...         435
287   [[1603405338,null,null,249],[1603405342,null,n...         435
288   [[1603497257,null,null,329],[1603497261,null,n...         435
289   [[1603683056,92,null,304],[1603683060,92,null,...         435
290   [[1603769480,null,null,392],[1603769484,null,n...         435
291   [[1603842540,84,null,192],[1603842544,85,null,...         435
292   [[1603938751,null,null,1079],[1603938755,null,...         435