## Emfit

### Sbt152

In [3]:
# Import 
import pandas as pd
import numpy as np
import os

# Show all columns
pd.set_option('display.max_columns', None)

# Define the directory where the log files are located
log_dir = "C:/Users/mathi/OneDrive/Skrivebord/2_Sem_Kand/Projekt_Kandidat2/Emfit/Sbt152/"

# Define the desired column names
desired_columns = ['id', 'device', 'user_id', 'from', 'to', 'avg_hr', 'avg_rr', 'avg_act',
        'calc_data', 'sleep_score', 'duration', 'duration_in_bed',
        'duration_awake', 'duration_in_sleep', 'duration_in_rem',
        'duration_in_light', 'duration_in_deep', 'duration_sleep_onset',
        'bedexit_duration', 'sleep_data', 'bedexit_count', 'bedexit_data',
        'tossnturn_count', 'tossnturn_data', 'from_gmt_offset', 'min_hr',
        'max_hr', 'min_rr', 'max_rr', 'fm_count', 'fm_data', 'awakenings',
        'hrv_data', 'hrv_score', 'hrv_lf', 'hrv_hf', 'hrv_rmssd_data',
        'hrv_rmssd_evening', 'hrv_rmssd_morning', 'temp_v1_uid']

# Create an empty dataframe with the desired column names
df = pd.DataFrame(columns=desired_columns)

# Loop over all the log files in the directory
for filename in os.listdir(log_dir):
    if filename.endswith(".log"):
        file_path = os.path.join(log_dir, filename)
        # print(f"Processing file {file_path}")
        
        # Read the log file into a temporary dataframe
        data = pd.read_json(file_path, lines=True)
        temp_df = pd.DataFrame(data)
        
        # Check if the temporary dataframe has all the desired columns
        if set(desired_columns).issubset(set(temp_df.columns)):
            # If it does, append it to the main dataframe
            df = pd.concat([df, temp_df[desired_columns]], ignore_index=True)

        else:
            # If it doesn't, create a new dataframe with only the columns that exist in the temporary dataframe
            # and append it to the main dataframe
            # print(f"File {file_path} has missing columns")
            missing_columns = set(desired_columns) - set(temp_df.columns)
            new_columns = [col for col in desired_columns if col not in missing_columns]
            df = pd.concat([df, temp_df[new_columns]], ignore_index=True)

# Display the resulting dataframe
df

,id,device,user_id,from,to,avg_hr,avg_rr,avg_act,calc_data,sleep_score,duration,duration_in_bed,duration_awake,duration_in_sleep,duration_in_rem,duration_in_light,duration_in_deep,duration_sleep_onset,bedexit_duration,sleep_data,bedexit_count,bedexit_data,tossnturn_count,tossnturn_data,from_gmt_offset,min_hr,max_hr,min_rr,max_rr,fm_count,fm_data,awakenings,hrv_data,hrv_score,hrv_lf,hrv_hf,hrv_rmssd_data,hrv_rmssd_evening,hrv_rmssd_morning,temp_v1_uid
0,59e9a40bd41d8c0045e62fc9,1F0B95,0,1508404086,1508484019,NaN,NaN,0,"[[1508483920,null,null,0],[1508483928,null,nul...",NaN,79933,79933,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,],0,,180,NaN,NaN,NaN,NaN,0,,NaN,NaN,0,0,0,[],NaN,NaN,0
1,59ec7241d41d8c004569fae0,1F0B95,0,1508627624,1508667920,63.4,12.5,130.7,"[[1508627625,null,null,60],[1508627629,null,nu...",112,40296,39450,3120,37170,10560,21720,4890,840,846,"[[1508627640,4],[1508628450,2],[1508629770,1],...",1,"[[1508644545,1508643699]]",260,"[1508627629,1508627709,1508627973,1508628229,1...",180,45,103,6,21,0,,3,"[[42.4,24.5,-17.9,0.58,-1.66],[47.6,32.1,-15.5...",35,45,55,"[[1508628794,47,42,58,0,0],[1508629694,50,37,6...",42.4,24.5,0
2,59edb8e2d41d8c0045a1f035,1F0B95,0,1508717933,1508751497,64.3,12.8,115.9,"[[1508717936,null,null,14],[1508717940,72,null...",84,33564,32075,5580,27990,5430,17250,5310,1710,1489,"[[1508717951,4],[1508719631,2],[1508720471,1],...",2,"[[1508745172,1508744839],[1508741440,1508740284]]",196,"[1508717972,1508718124,1508718160,1508718176,1...",180,54,78,7,19,0,,2,"[[32.7,40.1,7.4,1.23,0.80],[34.5,38.9,4.4,1.13...",50,44,56,"[[1508718023,57,51,49,0,0],[1508719643,48,46,5...",32.7,40.1,0
3,59eedcc8d41d8c0045c86f88,1F0B95,0,1508799247,1508826256,65.7,13.2,94.5,"[[1508799251,56,null,37],[1508799255,56,null,4...",78,27009,27009,3000,24000,2670,15120,6210,1980,0,"[[1508799266,4],[1508801216,2],[1508802026,1],...",0,],153,"[1508799291,1508799315,1508799371,1508799391,1...",180,55,115,8,26,0,,0,"[[33.1,32.3,-0.8,0.98,-0.11],[34.0,35.8,1.7,1....",42,49,51,"[[1508799877,28,29,71,0,0],[1508800237,30,30,7...",33.1,32.3,0
4,59ef153ed41d8c00450acbc8,1F0B95,0,1508831740,1508840683,64.9,14.4,160.2,"[[1508831743,60,null,19],[1508831747,58,null,1...",15,8943,8855,2880,6060,1050,4170,840,1380,88,"[[1508831758,4],[1508833108,2],[1508833768,4],...",1,"[[1508834628,1508834540]]",68,"[1508831799,1508831847,1508832067,1508832331,1...",180,48,95,8,18,0,,1,"[[38.6,50.7,12.2,1.32,4.98],[40.7,48.1,7.4,1.1...",69,38,62,"[[1508831830,51,29,71,0,0],[1508832190,29,40,6...",38.6,50.7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,5db7ca60d41d8c004be15449,1F0B95,NaN,1572297607,1572325935,61.3,14.2,80.1,"[[1572297608,null,null,57],[1572297612,null,nu...",78,28328,28231,2460,25860,7530,15180,3150,1350,97,"[[1572294023,4],[1572295343,2],[1572296063,4],...",1,"[[1572299756,1572299659]]",164,"[1572297756,1572298012,1572298240,1572298396,1...",120,45,120,6,25,0,,1,"[[12.6,19.2,6.6,1.52,1.09],[13.9,21.6,7.7,1.55...",22,34,66,"[[1572298596,16,22,78,0,233],[1572298777,16,26...",12.6,19.2,NaN
292,5db923dcd41d8c004bf0df55,1F0B95,NaN,1572386739,1572414409,60.8,14.9,90.8,"[[1572386743,null,null,96],[1572386747,null,nu...",80,27670,27670,2220,25440,7500,14130,3810,930,0,"[[1572383158,4],[1572384058,2],[1572385018,1],...",0,,168,"[1572386787,1572386803,1572386831,1572387027,1...",120,43,82,7,25,0,,0,"[[10.5,22.3,11.9,2.13,1.87],[12.3,22.1,9.8,1.8...",25,32,68,"[[1572384701,25,46,54,0,44],[1572385188,22,49,...",10.5,22.3,NaN
293,5db9ab04d41d8c004b38366d,1F0B95,NaN,1572441094,1572448977,69.3,6.1,30.5,"[[1572441095,null,null,39],[1572441099,null,nu...",15,7883,7736,2580,5310,1500,2670,1140,1770,147,"[[1572437510,4],[1572439250,2],[1572439550,3],...",1,"[[1572442499,1572442352]]",31,"[1572441471,1572441739,1572442003,1572442271,1...",120,45,84,4,9,0,,0,"[[18.9,27.5,8.7,1.46,28.91],[23.2,23.2,0.0,1.0...",29,34,66,"[[1572443308,14,30,70,1,41],[1572443488,19,32,...",18.9,27.5,NaN
294,5dba47fdd41d8c004b6001ee,1F0B95,NaN,1572470137,1572489165,62.4,14.4,71.7,"[[1572470141,null,null,73],[1572470145,null,nu...",47,19028,19028,3360,15660,2490,10020,3150,1980,0,"[[1572466556,4],[1572468506,2],[1572469976,1],...",0,,108,"[1572470193,1572470221,1572470425,1572470617,1...",120,44,79,6,20,0,,0,"[[12.3,20.9,8.6,1.70,2.26],[13.8,19.5,5.7,1.41...",22,39,61,"[[1572470407,16,44,56,0,282],[1572470586,15,49...",12.3,20.9,NaN
295,5dba7eb6d41d8c004b819abc,1F0B95,NaN,1572470137,1572503158,61.0,13.5,70.3,"[[1572470141,null,null,73],[1572470145,null,nu...",91,33021,32942,5280,27750,6240,14610,6900,1980,79,"[[1572466556,4],[1572468506,2],[1572469976,1],...",1,"[[1572489244,1572489165]]",186,"[1572470193,1572470221,1572470425,1572470617,1...",120,41,81,5,20,0,,1,"[[15.0,20.3,5.3,1.36,0.72],[13.6,17.5,3.9,1.29...",20,38,62,"[[1572470407,14,43,57,0,279],[1572470586,14,49...",15.0,20.3,NaN

### Sbt258

In [4]:
# Define the directory where the log files are located
log_dir = "C:/Users/mathi/OneDrive/Skrivebord/2_Sem_Kand/Projekt_Kandidat2/Emfit/Sbt258/"

# Define the desired column names
desired_columns = ['id', 'device', 'user_id', 'from', 'to', 'avg_hr', 'avg_rr', 'avg_act',
        'calc_data', 'sleep_score', 'duration', 'duration_in_bed',
        'duration_awake', 'duration_in_sleep', 'duration_in_rem',
        'duration_in_light', 'duration_in_deep', 'duration_sleep_onset',
        'bedexit_duration', 'sleep_data', 'bedexit_count', 'bedexit_data',
        'tossnturn_count', 'tossnturn_data', 'from_gmt_offset', 'min_hr',
        'max_hr', 'min_rr', 'max_rr', 'fm_count', 'fm_data', 'awakenings',
        'hrv_data', 'hrv_score', 'hrv_lf', 'hrv_hf', 'hrv_rmssd_data',
        'hrv_rmssd_evening', 'hrv_rmssd_morning', 'temp_v1_uid']

# Create an empty dataframe with the desired column names
df = pd.DataFrame(columns=desired_columns)

# Loop over all the log files in the directory
for filename in os.listdir(log_dir):
    if filename.endswith(".log"):
        file_path = os.path.join(log_dir, filename)
        # print(f"Processing file {file_path}")
        
        # Read the log file into a temporary dataframe
        data = pd.read_json(file_path, lines=True)
        temp_df = pd.DataFrame(data)
        
        # Check if the temporary dataframe has all the desired columns
        if set(desired_columns).issubset(set(temp_df.columns)):
            # If it does, append it to the main dataframe
            df = pd.concat([df, temp_df[desired_columns]], ignore_index=True)

        else:
            # If it doesn't, create a new dataframe with only the columns that exist in the temporary dataframe
            # and append it to the main dataframe
            # print(f"File {file_path} has missing columns")
            missing_columns = set(desired_columns) - set(temp_df.columns)
            new_columns = [col for col in desired_columns if col not in missing_columns]
            df = pd.concat([df, temp_df[new_columns]], ignore_index=True)

# Display the resulting dataframe
df

,id,device,user_id,from,to,avg_hr,avg_rr,avg_act,calc_data,sleep_score,duration,duration_in_bed,duration_awake,duration_in_sleep,duration_in_rem,duration_in_light,duration_in_deep,duration_sleep_onset,bedexit_duration,sleep_data,bedexit_count,bedexit_data,tossnturn_count,tossnturn_data,from_gmt_offset,min_hr,max_hr,min_rr,max_rr,fm_count,fm_data,awakenings,hrv_data,hrv_score,hrv_lf,hrv_hf,hrv_rmssd_data,hrv_rmssd_evening,hrv_rmssd_morning,temp_v1_uid
0,5a6c1bbe5f006d146cd6c3ba,001A89,NaN,1517006168,1517034363,53.8,13.1,260.9,"[[1517006169,null,null,265],[1517006173,null,n...",75,28195,28195,3870,24330,7590,12600,4140,1440,0,"[[1517006184,4],[1517007594,2],[1517007624,3],...",0,,136,"[1517006225,1517006273,1517006377,1517006469,1...",120,46,68,10,24,1,[1517033641],2,"[[17.1,16.9,-0.2,0.99,-0.03],[17.6,17.3,-0.2,0...",19,37,63,"[[1517006258,17,44,56,0,0],[1517006618,18,46,5...",17.1,16.9,NaN
1,5a6d7e0b113273146c22866b,001A89,NaN,1517089977,1517125088,48.5,13.2,225.7,"[[1517089978,null,null,922],[1517089982,null,n...",98,35111,34874,3330,31770,8340,18450,4980,1200,237,"[[1517089993,4],[1517091163,2],[1517092573,1],...",2,"[[1517097256,1517097110],[1517096720,1517096629]]",145,"[1517089982,1517090014,1517090086,1517090110,1...",120,43,76,8,25,0,,1,"[[14.0,30.8,16.8,2.20,1.75],[15.0,28.8,13.8,1....",33,40,60,"[[1517090426,14,59,41,0,0],[1517090786,15,57,4...",14.0,30.8,NaN
2,5a6ebc7b8f746f146c8a3f31,001A89,NaN,1517174451,1517206560,48.1,13.1,174.0,"[[1517174452,null,null,933],[1517174456,null,n...",88,32109,32109,3120,28980,8580,16590,3810,1530,0,"[[1517174467,4],[1517175967,2],[1517177197,1],...",0,,78,"[1517174460,1517174724,1517174756,1517174800,1...",120,41,57,10,24,0,,0,"[[18.7,21.1,2.4,1.13,0.27],[18.8,19.7,0.9,1.05...",23,49,51,"[[1517174542,22,36,64,0,0],[1517175081,20,39,6...",18.7,21.1,NaN
3,5a700e4a0a15cc146c38bde7,001A89,NaN,1517263254,1517293079,48.8,12.8,196.7,"[[1517263257,null,null,5417],[1517263261,null,...",84,29825,29676,3060,26760,8280,14160,4320,1020,149,"[[1517263272,4],[1517264262,2],[1517265702,1],...",1,"[[1517288550,1517288401]]",89,"[1517263257,1517263293,1517263313,1517263513,1...",120,43,59,10,23,0,,2,"[[23.8,14.7,-9.1,0.62,-1.13],[24.4,16.0,-8.4,0...",18,58,42,"[[1517263344,22,36,64,0,0],[1517263704,25,35,6...",23.8,14.7,NaN
4,5a71520708b589146c6ae394,001A89,NaN,1517350454,1517375944,47.4,12.8,218.0,"[[1517350457,null,null,131],[1517350461,null,n...",74,25490,25490,2280,23220,6570,12480,4170,870,0,"[[1517350472,4],[1517351312,2],[1517352902,1],...",0,,77,"[1517350485,1517352389,1517352409,1517352429,1...",120,42,59,10,23,0,,2,"[[25.3,15.8,-9.5,0.63,-1.36],[27.3,16.6,-10.6,...",19,51,49,"[[1517350544,29,29,71,0,0],[1517350904,29,29,7...",25.3,15.8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,5d256570a248c32848aa5759,001A89,NaN,1562705684,1562731837,66.6,13.3,192.9,"[[1562705685,null,null,369],[1562705689,null,n...",71,26153,26153,2820,23340,4350,14760,4230,1500,0,"[[1562705700,4],[1562707170,2],[1562708850,1],...",0,,81,"[1562705705,1562705725,1562705745,1562705773,1...",180,58,127,10,25,0,,1,"[[18.0,10.4,-7.6,0.58,-1.15],[20.3,12.7,-7.6,0...",19,54,46,"[[1562707214,37,77,23,1,44],[1562707574,35,75,...",18.0,10.4,NaN
501,5d26d1039249b62848763599,001A89,NaN,1562791372,1562824940,67.7,13.5,211.1,"[[1562791374,null,null,130],[1562791378,69,nul...",97,33568,33568,2820,30750,7080,18090,5580,600,0,"[[1562791389,4],[1562791959,2],[1562794149,3],...",0,,135,"[1562791422,1562791486,1562791502,1562791626,1...",180,59,113,10,20,0,,1,"[[9.0,15.5,6.5,1.72,0.84],[8.4,11.8,3.3,1.40,0...",18,53,47,"[[1562794701,8,42,58,0,37],[1562794882,8,50,50...",9.0,15.5,NaN
502,5d2818798ef8e528485e0139,001A89,NaN,1562879467,1562908769,65.7,13.0,233.6,"[[1562879469,63,6.6,0],[1562879473,63,6.6,0],[...",77,29302,29302,3810,25500,4140,16410,4950,1620,0,"[[1562879484,4],[1562881074,2],[1562882004,1],...",0,,113,"[1562879609,1562879625,1562879641,1562879665,1...",180,58,125,7,22,0,,2,"[[9.7,15.8,6.0,1.62,0.88],[12.2,17.4,5.2,1.43,...",20,59,41,"[[1562882436,10,35,65,0,28],[1562882616,11,41,...",9.7,15.8,NaN
503,5d28277169cc142848e37e59,001A89,NaN,1562879467,1562912567,65.8,13.0,262.9,"[[1562879469,63,6.6,0],[1562879473,63,6.6,0],[...",88,33100,32839,4110,28980,4740,18510,5730,1620,261,"[[1562879484,4],[1562881074,2],[1562881974,1],...",1,"[[1562909030,1562908769]]",160,"[1562879609,1562879625,1562879641,1562879665,1...",180,58,125,7,22,1,[1562912295],3,"[[10.5,15.6,5.1,1.49,0.65],[12.1,15.7,3.6,1.29...",18,54,46,"[[1562882436,10,36,64,1,28],[1562882616,11,42,...",10.5,15.6,NaN
504,5d2971402e1dba2848805ed7,001A89,NaN,1562965223,1562996975,64.8,13.5,259.1,"[[1562965225,65,null,260],[1562965229,64,null,...",82,31752,31533,4650,27090,8160,14970,3960,2970,219,"[[1562965240,4],[1562968180,2],[1562968300,1],...",1,"[[1562996038,1562995819]]",186,"[1562965373,1562965389,1562965405,1562965421,1...",180,54,130,10,23,2,"[1562996546,1562996578]",0,"[[11.3,15.2,3.9,1.34,0.52],[10.3,13.0,2.7,1.26...",16,52,48,"[[1562968193,10,73,27,1,190],[1562968373,10,70...",11.3,15.2,NaN