In [19]:
# Import Pandas
import pandas as pd

# Show all columns
pd.set_option('display.max_columns', None)

# Read Data.csv
data = pd.read_csv('C:/Users/mathi/OneDrive/Skrivebord/2_Sem_Kand/Projekt_Kandidat2/Data.csv')

data

,Unnamed: 0,id,device,user_id,from,to,avg_hr,avg_rr,avg_act,calc_data,sleep_score,duration,duration_in_bed,duration_awake,duration_in_sleep,duration_in_rem,duration_in_light,duration_in_deep,duration_sleep_onset,bedexit_duration,sleep_data,bedexit_count,bedexit_data,tossnturn_count,tossnturn_data,from_gmt_offset,min_hr,max_hr,min_rr,max_rr,fm_count,fm_data,awakenings,hrv_data,hrv_score,hrv_lf,hrv_hf,hrv_rmssd_data,hrv_rmssd_evening,hrv_rmssd_morning,temp_v1_uid,patient_ID
0,0,59e9a40bd41d8c0045e62fc9,1F0B95,0.0,1508404086,1508484019,NaN,NaN,0.0,"[[1508483920,null,null,0],[1508483928,null,nul...",NaN,79933,79933,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,],0,NaN,180,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,0.0,[],NaN,NaN,0.0,152
1,1,59ec7241d41d8c004569fae0,1F0B95,0.0,1508627624,1508667920,63.4,12.5,130.7,"[[1508627625,null,null,60],[1508627629,null,nu...",112.0,40296,39450,3120.0,37170.0,10560.0,21720.0,4890.0,840.0,846,"[[1508627640,4],[1508628450,2],[1508629770,1],...",1,"[[1508644545,1508643699]]",260,"[1508627629,1508627709,1508627973,1508628229,1...",180,45.0,103.0,6.0,21.0,0,NaN,3.0,"[[42.4,24.5,-17.9,0.58,-1.66],[47.6,32.1,-15.5...",35.0,45.0,55.0,"[[1508628794,47,42,58,0,0],[1508629694,50,37,6...",42.4,24.5,0.0,152
2,2,59edb8e2d41d8c0045a1f035,1F0B95,0.0,1508717933,1508751497,64.3,12.8,115.9,"[[1508717936,null,null,14],[1508717940,72,null...",84.0,33564,32075,5580.0,27990.0,5430.0,17250.0,5310.0,1710.0,1489,"[[1508717951,4],[1508719631,2],[1508720471,1],...",2,"[[1508745172,1508744839],[1508741440,1508740284]]",196,"[1508717972,1508718124,1508718160,1508718176,1...",180,54.0,78.0,7.0,19.0,0,NaN,2.0,"[[32.7,40.1,7.4,1.23,0.80],[34.5,38.9,4.4,1.13...",50.0,44.0,56.0,"[[1508718023,57,51,49,0,0],[1508719643,48,46,5...",32.7,40.1,0.0,152
3,3,59eedcc8d41d8c0045c86f88,1F0B95,0.0,1508799247,1508826256,65.7,13.2,94.5,"[[1508799251,56,null,37],[1508799255,56,null,4...",78.0,27009,27009,3000.0,24000.0,2670.0,15120.0,6210.0,1980.0,0,"[[1508799266,4],[1508801216,2],[1508802026,1],...",0,],153,"[1508799291,1508799315,1508799371,1508799391,1...",180,55.0,115.0,8.0,26.0,0,NaN,0.0,"[[33.1,32.3,-0.8,0.98,-0.11],[34.0,35.8,1.7,1....",42.0,49.0,51.0,"[[1508799877,28,29,71,0,0],[1508800237,30,30,7...",33.1,32.3,0.0,152
4,4,59ef153ed41d8c00450acbc8,1F0B95,0.0,1508831740,1508840683,64.9,14.4,160.2,"[[1508831743,60,null,19],[1508831747,58,null,1...",15.0,8943,8855,2880.0,6060.0,1050.0,4170.0,840.0,1380.0,88,"[[1508831758,4],[1508833108,2],[1508833768,4],...",1,"[[1508834628,1508834540]]",68,"[1508831799,1508831847,1508832067,1508832331,1...",180,48.0,95.0,8.0,18.0,0,NaN,1.0,"[[38.6,50.7,12.2,1.32,4.98],[40.7,48.1,7.4,1.1...",69.0,38.0,62.0,"[[1508831830,51,29,71,0,0],[1508832190,29,40,6...",38.6,50.7,0.0,152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21866,21866,63fe92952f91ec18484a1c33,11EC56,NaN,1677620134,1677627980,61.2,16.1,608.1,"[[1677620138,null,null,405],[1677620142,null,n...",18.0,7846,7846,1920.0,5910.0,1140.0,3390.0,1380.0,840.0,0,"[[1677620153,4],[1677620963,2],[1677623063,1],...",0,NaN,102,"[1677620146,1677620162,1677620178,1677620194,1...",120,54.0,114.0,10.0,26.0,0,NaN,0.0,"[[23.6,38.5,14.9,1.63,9.61],[30.4,31.7,1.4,1.0...",46.0,25.0,75.0,"[[1677621124,21,29,71,0,680],[1677621665,22,28...",23.6,38.5,NaN,586
21867,21867,63fef84eef176518489aba2c,11EC56,NaN,1677620134,1677654035,60.2,15.8,468.6,"[[1677620138,null,null,405],[1677620142,null,n...",89.0,33901,33557,4200.0,29700.0,7980.0,17430.0,4290.0,840.0,344,"[[1677620153,4],[1677620963,2],[1677623033,1],...",2,"[[1677653086,1677652879],[1677628117,1677627980]]",274,"[1677620146,1677620162,1677620178,1677620194,1...",120,49.0,126.0,10.0,26.0,0,NaN,1.0,"[[35.0,21.7,-13.3,0.62,-1.55],[29.0,21.6,-7.4,...",25.0,32.0,68.0,"[[1677621124,22,29,71,0,680],[1677621665,22,28...",35.0,21.7,NaN,586
21868,21868,64002e9c82af5e1848c39a00,11EC56,NaN,1677707752,1677733460,61.7,16.6,451.9,"[[1677707755,null,null,9560],[1677707759,null,...",68.0,25708,25642,3420.0,22290.0,7080.0,12150.0,3060.0,1830.0,66,"[[1677707770,4],[1677709570,2],[1677711400,3],...",1,"[[1677733448,1677733382]]",192,"[1677707779,1677707795,1677707827,1677707847,1...",120,49.0,125.0,12.0,26.0,0,NaN,0.0,"[[70.7,31.1,-39.6,0.44,-6.49],[69.1,39.1,-30.0...",44.0,33.0,67.0,"[[1677709822,54,27,73,0,188],[1677710002,60,27...",70.7,31.1,NaN,586
21869,21869,640142b5c0869a1848a5de45,11EC56,NaN,1677794122,1677804160,59.5,15.3,453.4,"[[1677794126,null,null,6057],[1677794130,null,...",27.0,10038,10038,1320.0,8700.0,2850.0,4590.0,1260.0,1050.0,0,"[[1677794141,4],[1677795161,2],[1677796631,1],...",0,NaN,71,"[1677794138,1677794154,1677794178,1677794198,1...",120,55.0,72.0,13.0,26.0,0,NaN,0.0,"[[9.4,68.0,58.6,7.27,25.43],[26.4,47.9,21.5,1....",77.0,36.0,64.0,"[[1677795293,25,51,49,0,107],[1677795473,24,46...",9.4,68.0,NaN,586
21870,21870,640185861eab4c1848f78672,11EC56,NaN,1677794122,1677821258,58.3,15.6,439.2,"[[1677794126,null,null,6057],[1677794130,null,...",71.0,27136,27019,2940.0,24180.0,8250.0,13290.0,2640.0,1020.0,117,"[[1677794141,4],[1677795131,2],[1677796601,1],...",1,"[[1677804277,1677804160]]",184,"[1677794138,1677794154,1677794178,1677794198,1...",120,49.0,117.0,13.0,26.0,0,NaN,3.0,"[[43.6,28.7,-14.8,0.66,-2.11],[26.6,22.1,-4.5,...",31.0,31.0,69.0,"[[1677795293,26,48,52,0,104],[1677795473,25,44...",43.6,28.7,NaN,586

In [48]:
# Read Data.csv
df_patientInfo = pd.read_excel('Data_om_patienter.xlsx')
# Remove 'subject_ID' == Gennemsnit
df_patientInfo = df_patientInfo[df_patientInfo.subject_ID != 'Gennemsnit']

df_patientInfo.tail(5)

,subject_ID,FPx,EF_number,emfit_device_id,age_baseline,gender,NYHA_baseline,ef_titration,ef_rehabilitation,ef_finished,weight_baseline,height_baseline,bp_sys_baseline,bp_dia_baseline,heart_rate_baseline,first_measure,last_measure,Total_days,Beskrivelse
30,539,38.0,EF38g,1C6930,74.0,0.0,2.0,30.0,35.0,NaN,107.0,176.0,116.0,74.0,89.0,NaT,NaT,NaN,Har pacemaker
31,545,41.0,EF33g,1C6FEE,48.0,0.0,2.0,35.0,NaN,45.0,132.0,190.0,144.0,93.0,63.0,2022-12-14 05:03:54,2023-03-07 05:42:10,83.026574,NaN
32,548,40.0,EF39g,1C6943,60.0,0.0,2.0,25.0,NaN,NaN,107.5,178.0,108.0,73.0,81.0,2022-12-14 07:05:02,2022-12-25 19:57:03,11.536123,NaN
33,552,42.0,EF41g,1C6FF8,65.0,0.0,2.0,20.0,NaN,NaN,100.0,178.0,120.0,66.0,65.0,2022-12-22 04:07:21,2023-03-07 05:54:52,75.074664,NaN
34,554,43.0,EF36g,1C6994,74.0,0.0,2.0,20.0,NaN,NaN,74.0,183.0,116.0,72.0,74.0,2022-12-22 04:42:08,2023-03-07 04:15:45,74.981678,NaN

### Set Emfit & FP2 sammen

In [49]:

# Make a list of unique values in the column 'subject_ID'
unique_subject_ID = df_patientInfo['subject_ID'].unique()
# print(unique_subject_ID) # [431 435 440 448 451 453 454 457 459 462 465 468 469 477 478 483 485 492
#  # 494 495 499 504 510 513 515 516 518 520 524 526 539 545 548 552 554]

# Print unique values in the column 'patient_ID'
unique_patient_ID = data['patient_ID'].unique() 
# print(unique_patient_ID)  # [152 258 261 264 271 283 285 286 294 299 300 301 318 323 327 329 332 342
#  350 352 353 360 361 376 383 386 402 403 404 405 406 407 408 409 410 411
#  412 413 414 415 416 417 418 419 420 421 431 435 440 448 451 454 459 462
#  465 468 469 477 485 492 494 495 504 510 513 515 516 520 524 526 545 548
#  552 554 560 563 564 569 571 583 586]

# # Which values in unique_patient_ID are not in unique_subject_ID
# print(set(unique_patient_ID) - set(unique_subject_ID)) 


# For loop through the list and where unique_subject_ID is == patient_ID in dataframe data then make new column age_baseline	gender	NYHA_baseline	ef_titration	ef_rehabilitation	ef_finished	weight_baseline	height_baseline	bp_sys_baseline	bp_dia_baseline	heart_rate_baseline and add the values from the dataframe df_patientInfo

# for i in unique_subject_ID:
#     data.loc[data['patient_ID'] == i, 'AGEBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'age_baseline'].values[0]
#     data.loc[data['patient_ID'] == i, 'GENDER'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'gender'].values[0]
#     data.loc[data['patient_ID'] == i, 'NYHABL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'NYHA_baseline'].values[0]
#     data.loc[data['patient_ID'] == i, 'EFTITBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'ef_titration'].values[0]
#     data.loc[data['patient_ID'] == i, 'EJREHABBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'ef_rehabilitation'].values[0]
#     data.loc[data['patient_ID'] == i, 'EJFINISHBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'ef_finished'].values[0]
#     data.loc[data['patient_ID'] == i, 'WEIGHTBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'weight_baseline'].values[0]
#     data.loc[data['patient_ID'] == i, 'HEIGHTBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'height_baseline'].values[0]
#     data.loc[data['patient_ID'] == i, 'BPSYSBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'bp_sys_baseline'].values[0]
#     data.loc[data['patient_ID'] == i, 'BPDIABL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'bp_dia_baseline'].values[0]
#     data.loc[data['patient_ID'] == i, 'HRB'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'heart_rate_baseline'].values[0]

# data

# # Print data for patient_ID == 524
# data.loc[data['patient_ID'] == 524]

# for i in newListOfPatients:
#     df_dataPreb.loc[df_dataPreb['id_Patient'] == i, 'AGE'] = df_redcap.loc[df_redcap['id_Patient'] == i, 'AlderInklusion'].values[0]

{258, 386, 261, 264, 271, 402, 403, 404, 405, 406, 407, 152, 408, 409, 283, 410, 285, 286, 411, 412, 413, 414, 415, 416, 417, 294, 418, 419, 420, 421, 299, 300, 301, 560, 563, 564, 569, 571, 318, 323, 583, 327, 329, 586, 332, 342, 350, 352, 353, 360, 361, 376, 383}