In [20]:
# Import Pandas
import pandas as pd

# Show all columns
pd.set_option('display.max_columns', None)

# Read Data.csv
data = pd.read_csv('C:/Users/mathi/OneDrive/Skrivebord/2_Sem_Kand/Projekt_Kandidat2/Projekt_Kandidat2/Data1.csv')
data

,Unnamed: 0,id,device,from,to,avg_hr,avg_rr,avg_act,calc_data,sleep_score,duration,duration_in_bed,duration_awake,duration_in_sleep,duration_in_rem,duration_in_light,duration_in_deep,duration_sleep_onset,bedexit_duration,sleep_data,bedexit_count,bedexit_data,tossnturn_count,tossnturn_data,from_gmt_offset,min_hr,max_hr,min_rr,max_rr,fm_count,fm_data,awakenings,hrv_data,hrv_score,hrv_lf,hrv_hf,hrv_rmssd_data,hrv_rmssd_evening,hrv_rmssd_morning,temp_v1_uid,patient_ID,from_datetime,"Blodtryk, Systolisk","Blodtryk, Diastolisk",Puls,VÃ¦gt,Skridt
0,0,59e9a40bd41d8c0045e62fc9,1F0B95,1508404086,1508484019,NaN,NaN,0.0,"[[1508483920,null,null,0],[1508483928,null,nul...",NaN,79933,79933,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,],0,NaN,180,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,0.0,[],NaN,NaN,0.0,152,2017-10-19 09:08:06,NaN,NaN,NaN,NaN,NaN
1,1,59ec7241d41d8c004569fae0,1F0B95,1508627624,1508667920,63.4,12.5,130.7,"[[1508627625,null,null,60],[1508627629,null,nu...",112.0,40296,39450,3120.0,37170.0,10560.0,21720.0,4890.0,840.0,846,"[[1508627640,4],[1508628450,2],[1508629770,1],...",1,"[[1508644545,1508643699]]",260,"[1508627629,1508627709,1508627973,1508628229,1...",180,45.0,103.0,6.0,21.0,0,NaN,3.0,"[[42.4,24.5,-17.9,0.58,-1.66],[47.6,32.1,-15.5...",35.0,45.0,55.0,"[[1508628794,47,42,58,0,0],[1508629694,50,37,6...",42.4,24.5,0.0,152,2017-10-21 23:13:44,NaN,NaN,NaN,NaN,NaN
2,2,59edb8e2d41d8c0045a1f035,1F0B95,1508717933,1508751497,64.3,12.8,115.9,"[[1508717936,null,null,14],[1508717940,72,null...",84.0,33564,32075,5580.0,27990.0,5430.0,17250.0,5310.0,1710.0,1489,"[[1508717951,4],[1508719631,2],[1508720471,1],...",2,"[[1508745172,1508744839],[1508741440,1508740284]]",196,"[1508717972,1508718124,1508718160,1508718176,1...",180,54.0,78.0,7.0,19.0,0,NaN,2.0,"[[32.7,40.1,7.4,1.23,0.80],[34.5,38.9,4.4,1.13...",50.0,44.0,56.0,"[[1508718023,57,51,49,0,0],[1508719643,48,46,5...",32.7,40.1,0.0,152,2017-10-23 00:18:53,NaN,NaN,NaN,NaN,NaN
3,3,59eedcc8d41d8c0045c86f88,1F0B95,1508799247,1508826256,65.7,13.2,94.5,"[[1508799251,56,null,37],[1508799255,56,null,4...",78.0,27009,27009,3000.0,24000.0,2670.0,15120.0,6210.0,1980.0,0,"[[1508799266,4],[1508801216,2],[1508802026,1],...",0,],153,"[1508799291,1508799315,1508799371,1508799391,1...",180,55.0,115.0,8.0,26.0,0,NaN,0.0,"[[33.1,32.3,-0.8,0.98,-0.11],[34.0,35.8,1.7,1....",42.0,49.0,51.0,"[[1508799877,28,29,71,0,0],[1508800237,30,30,7...",33.1,32.3,0.0,152,2017-10-23 22:54:07,NaN,NaN,NaN,NaN,NaN
4,4,59ef153ed41d8c00450acbc8,1F0B95,1508831740,1508840683,64.9,14.4,160.2,"[[1508831743,60,null,19],[1508831747,58,null,1...",15.0,8943,8855,2880.0,6060.0,1050.0,4170.0,840.0,1380.0,88,"[[1508831758,4],[1508833108,2],[1508833768,4],...",1,"[[1508834628,1508834540]]",68,"[1508831799,1508831847,1508832067,1508832331,1...",180,48.0,95.0,8.0,18.0,0,NaN,1.0,"[[38.6,50.7,12.2,1.32,4.98],[40.7,48.1,7.4,1.1...",69.0,38.0,62.0,"[[1508831830,51,29,71,0,0],[1508832190,29,40,6...",38.6,50.7,0.0,152,2017-10-24 07:55:40,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23039,23039,6440cb180f86201dbc628e9a,1C6C39,1681942129,1681967833,69.6,13.3,164.8,"[[1681942132,null,null,16136],[1681942136,null...",69.0,25704,25704,1890.0,23820.0,6570.0,15150.0,2100.0,1560.0,0,"[[1681942147,4],[1681943677,2],[1681944667,3],...",0,NaN,83,"[1681942144,1681942160,1681942192,1681943188,1...",180,48.0,94.0,9.0,26.0,0,NaN,0.0,NaN,0.0,0.0,0.0,[],NaN,NaN,NaN,623,2023-04-19 22:08:49,NaN,NaN,NaN,89.95,5483.0
23040,23040,644215bccd27cc1dbcaa3ff1,1C6C39,1682026595,1682052489,58.1,12.6,153.3,"[[1682026599,null,null,79],[1682026603,null,nu...",77.0,25894,25894,2730.0,23160.0,5400.0,12270.0,5490.0,840.0,0,"[[1682026614,4],[1682027424,2],[1682028954,3],...",0,NaN,120,"[1682026623,1682026639,1682026655,1682026683,1...",180,46.0,113.0,6.0,23.0,0,NaN,1.0,"[[27.8,37.0,9.3,1.33,1.61],[32.2,35.1,2.9,1.09...",51.0,40.0,60.0,"[[1682028665,39,69,31,0,69],[1682030645,37,64,...",27.8,37.0,NaN,623,2023-04-20 21:36:35,149.0,92.0,81.0,88.70,7065.0
23041,23041,64437c29ed11011dbccac6e0,1C6C39,1682120328,1682144242,60.9,12.6,111.9,"[[1682120331,null,null,102],[1682120335,null,n...",70.0,23914,23914,2430.0,21480.0,7560.0,10260.0,3660.0,1320.0,0,"[[1682120346,4],[1682121636,2],[1682122596,3],...",0,NaN,54,"[1682120363,1682120615,1682120911,1682121111,1...",180,45.0,91.0,7.0,24.0,0,NaN,0.0,"[[22.9,27.2,4.3,1.19,1.00],[25.4,26.7,1.3,1.05...",47.0,43.0,57.0,"[[1682125277,31,58,42,1,49],[1682127078,27,54,...",22.9,27.2,NaN,623,2023-04-21 23:38:48,NaN,NaN,NaN,NaN,9596.0
23042,23042,6444b4b15ba07122f0925461,1C6C39,1682200267,1682223935,55.7,12.0,142.0,"[[1682200271,null,null,204],[1682200275,null,n...",63.0,23668,23668,3420.0,20250.0,5610.0,10920.0,3720.0,1920.0,0,"[[1682200286,4],[1682202176,2],[1682203406,1],...",0,NaN,83,"[1682200275,1682200291,1682200975,1682200987,1...",180,48.0,98.0,9.0,25.0,0,NaN,1.0,"[[20.8,31.0,10.2,1.49,2.07],[18.5,26.9,8.4,1.4...",32.0,31.0,69.0,"[[1682202337,22,56,44,0,135],[1682202517,20,50...",20.8,31.0,NaN,623,2023-04-22 21:51:07,NaN,NaN,NaN,NaN,12274.0
23043,23043,6446136eb74d1522f06bf5de,1C6C39,1682291989,1682314021,62.0,11.7,121.2,"[[1682291991,63,null,45],[1682292026,61,null,5...",66.0,22032,22032,1050.0,20970.0,7320.0,10950.0,2700.0,660.0,0,"[[1682292006,4],[1682292636,2],[1682293836,1],...",0,NaN,62,"[1682292218,1682292830,1682293086,1682293630,1...",180,49.0,113.0,8.0,25.0,0,NaN,1.0,"[[30.0,16.1,-13.8,0.54,-6.28],[26.0,21.7,-4.3,...",32.0,43.0,57.0,"[[1682292649,26,30,70,0,117],[1682292829,25,30...",30.0,16.1,NaN,623,2023-04-23 23:19:49,NaN,NaN,NaN,NaN,9695.0

In [21]:
# Read Data.csv
df_patientInfo = pd.read_excel('C:/Users/mathi/OneDrive/Skrivebord/2_Sem_Kand/Projekt_Kandidat2/Data_om_patienter.xlsx')

# Remove 'subject_ID' == Gennemsnit
df_patientInfo = df_patientInfo[df_patientInfo.subject_ID != 'Gennemsnit']

df_patientInfo.tail(10)

,subject_ID,age_baseline,gender,NYHA_baseline,ef_titration,ef_rehabilitation,ef_finished,weight_baseline,height_baseline,bp_sys_baseline,bp_dia_baseline,heart_rate_baseline
45,584,60,0,2.0,60.0,NaN,NaN,72.0,172,140,90,70
46,564,69,0,3.0,50.0,NaN,NaN,105.0,189,131,65,63
47,592,63,0,NaN,55.0,NaN,NaN,98.0,190,120,90,62
48,597,76,1,1.0,60.0,NaN,NaN,70.0,169,140,85,63
49,601,70,0,1.0,60.0,NaN,NaN,83.0,177,135,79,62
50,606,81,1,3.0,60.0,NaN,NaN,68.0,161,127,69,53
51,610,57,1,NaN,60.0,NaN,NaN,129.5,175,131,76,63
52,612,56,0,3.0,50.0,NaN,NaN,95.0,176,116,86,89
53,620,57,0,2.0,60.0,NaN,NaN,70.0,166,105,75,65
54,623,69,0,1.0,60.0,NaN,NaN,85.0,169,126,77,57

### Set Emfit & FP2 sammen

In [22]:

# Make a list of unique values in the column 'subject_ID'
unique_subject_ID = df_patientInfo['subject_ID'].unique()
# print(unique_subject_ID) # [431 435 440 448 451 453 454 457 459 462 465 468 469 477 478 483 485 492
#  494 495 499 504 510 513 515 516 518 520 524 526 539 545 548 552 554 586
#  583 593 580 579 568 560 571 563 569 584 564 592 597 601 606 610 612 620
#  623]

# Print unique values in the column 'patient_ID'
unique_patient_ID = data['patient_ID'].unique() 
# print(unique_patient_ID)  # [152 258 261 264 271 283 285 286 294 299 300 301 318 323 327 329 332 342
#  350 352 353 360 361 376 383 386 402 403 404 405 406 407 408 409 410 411
#  412 413 414 415 416 417 418 419 420 421 431 435 440 448 451 454 459 462
#  465 468 469 477 485 492 494 495 504 510 513 515 516 520 524 526 545 548
#  552 554 560 563 564 569 571 583 586 579 580 584 592 593 597 601 606 610
#  612 620 623]

# # Which values in unique_patient_ID are not in unique_subject_ID
# print(set(unique_patient_ID) - set(unique_subject_ID))

# Only keep the values in data['patient_ID'] that are in unique_subject_ID
data = data[data['patient_ID'].isin(unique_subject_ID)]


# # For loop through the list and where unique_subject_ID is == patient_ID in dataframe data then make new column age_baseline	gender	NYHA_baseline	ef_titration	ef_rehabilitation	ef_finished	weight_baseline	height_baseline	bp_sys_baseline	bp_dia_baseline	heart_rate_baseline and add the values from the dataframe df_patientInfo

for i in unique_subject_ID:
    data.loc[data['patient_ID'] == i, 'AGEBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'age_baseline'].values[0]
    data.loc[data['patient_ID'] == i, 'GENDER'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'gender'].values[0]
    data.loc[data['patient_ID'] == i, 'NYHABL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'NYHA_baseline'].values[0]
    data.loc[data['patient_ID'] == i, 'EFTITBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'ef_titration'].values[0]
    data.loc[data['patient_ID'] == i, 'EJREHABBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'ef_rehabilitation'].values[0]
    data.loc[data['patient_ID'] == i, 'EJFINISHBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'ef_finished'].values[0]
    data.loc[data['patient_ID'] == i, 'WEIGHTBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'weight_baseline'].values[0]
    data.loc[data['patient_ID'] == i, 'HEIGHTBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'height_baseline'].values[0]
    data.loc[data['patient_ID'] == i, 'BPSYSBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'bp_sys_baseline'].values[0]
    data.loc[data['patient_ID'] == i, 'BPDIABL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'bp_dia_baseline'].values[0]
    data.loc[data['patient_ID'] == i, 'HRB'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'heart_rate_baseline'].values[0]

# data

# # # # Print data for patient_ID == 524
# # # data.loc[data['patient_ID'] == 524]

# Save as new csv file
data.to_csv('Data2.csv', index=False)

[431 435 440 448 451 453 454 457 459 462 465 468 469 477 478 483 485 492
 494 495 499 504 510 513 515 516 518 520 524 526 539 545 548 552 554 586
 583 593 580 579 568 560 571 563 569 584 564 592 597 601 606 610 612 620
 623]

C:\Users\mathi\AppData\Local\Temp\ipykernel_19284\2622833497.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data['patient_ID'] == i, 'AGEBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'age_baseline'].values[0]
C:\Users\mathi\AppData\Local\Temp\ipykernel_19284\2622833497.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data['patient_ID'] == i, 'GENDER'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'gender'].values[0]
C:\Users\mathi\AppData\Local\Temp\ipykernel_19284\2622833497.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data['patient_ID'] == i, 'NYHABL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'NYHA_baseline'].values[0]
C:\Users\mathi\AppData\Local\Temp\ipykernel_19284\2622833497.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data['patient_ID'] == i, 'EFTITBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'ef_titration'].values[0]
C:\Users\mathi\AppData\Local\Temp\ipykernel_19284\2622833497.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data['patient_ID'] == i, 'EJREHABBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'ef_rehabilitation'].values[0]
C:\Users\mathi\AppData\Local\Temp\ipykernel_19284\2622833497.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data['patient_ID'] == i, 'EJFINISHBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'ef_finished'].values[0]
C:\Users\mathi\AppData\Local\Temp\ipykernel_19284\2622833497.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data['patient_ID'] == i, 'WEIGHTBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'weight_baseline'].values[0]
C:\Users\mathi\AppData\Local\Temp\ipykernel_19284\2622833497.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data['patient_ID'] == i, 'HEIGHTBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'height_baseline'].values[0]
C:\Users\mathi\AppData\Local\Temp\ipykernel_19284\2622833497.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data['patient_ID'] == i, 'BPSYSBL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'bp_sys_baseline'].values[0]
C:\Users\mathi\AppData\Local\Temp\ipykernel_19284\2622833497.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data['patient_ID'] == i, 'BPDIABL'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'bp_dia_baseline'].values[0]
C:\Users\mathi\AppData\Local\Temp\ipykernel_19284\2622833497.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data['patient_ID'] == i, 'HRB'] = df_patientInfo.loc[df_patientInfo['subject_ID'] == i, 'heart_rate_baseline'].values[0]